trigger:
- neos-release

strategy:
  matrix:
    #linux:
    #  imageName: 'ubuntu-latest'
    #  cmakeTarget: 'Unix Makefiles'
    #  sourceFolder: 'bin/'
    #  sourceFile: 'libassimp.so'
    #  targetFile: 'Assimp64.so'
    #  artifactName : 'linux_x64'
    windows:
      imageName: 'windows-latest'
      cmakeTarget: 'Visual Studio 16 2019'
      sourceFolder: 'bin/Release/'
      sourceFile: 'assimp-vc142-mt.dll'
      targetFile: 'Assimp64.dll'
      artifactName : 'windows_x64'

pool:
  vmImage: $(imageName)

steps:
- task: CMake@1
  inputs:
    workingDirectory: 
    cmakeArgs: 'CMakeLists.txt -G "$(cmakeTarget)"'

- task: CmdLine@2
  inputs:
    script: 'tree /F /A'

- task: VSBuild@1
  inputs:
    solution: 'crnlib.sln'
    vsVersion: '16.0'
    platform: 'x64'
    configuration: 'release_DLL'
    msbuildArchitecture: 'x64'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$(ANDROID_NDK_PATH)/ndk-build'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      make
      dir .
  condition: eq( variables['Agent.OS'], 'Linux' )
  
- task: CmdLine@2
  inputs:
    script: 'tree /F /A'